### ISSUE TITLE
Dleft: correction of distances

### ISSUE THREAD

**Issue by therese3** [yakir12/MAT2db.jl#43]
In Displacement left, I realized that when the distance between the nest and the initial feeder is corrected to 130 cm, the distance between the initial feeder and the feeder also decreases. Sometimes from the correct distance to a shorter distance.... can we fix this?

**Comment by yakir12** [comment]
If this run has three POIs for which we expect:
1. nest 0 0
2. initialfeeder 0 -130
3. feeder -50 -130
then that is very strange indeed. Please send me the file from running the `debugging` function.

**Comment by yakir12** [comment]
And if indeed this is the case, please paste the link to the uploaded file here, this way I'll be able to associate that file with this issue. Thanks!
